package module

import (
	"context"
	apitype "sayo_framework/pkg/type/api_type"
	"sayo_framework/pkg/type/cast"
	"sayo_framework/pkg/utils"
	"sayo_framework/service"
	"sayo_framework/service/module"

	"github.com/kataras/iris/v12"
)

/*
POST /module

	json: {
		modules: [
			{
				path:string 	// Prefix path for module register.json
				uuid:string 	// generated by the front-end to distinguish modules
			}
		]
	}
*/
func RegisterModule(svc *service.ServiceContext) utils.HandlerFunc {
	return utils.IrisCtxJSONWrap(func(ctx iris.Context) (*apitype.BaseResp, error) {
		var req *apitype.RegisterModulesReq
		if err := ctx.ReadJSON(&req); err != nil {
			return apitype.NewBaseRespByError(err), err
		}

		resp, err := module.NewModuleServer(context.Background(), svc).RegisterModules(cast.RegisterModulesReq(req))
		if err != nil {
			return apitype.NewBaseRespByError(err).WithData(resp), err
		}

		return apitype.NewSuccessResp(nil), nil
	})
}
